id: ID7B9ABF3
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T07:50:46+00:00'
last_modified: '2022-06-08T09:13:01.004189+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG2807
  title: མཁས་འཇུག་གི་ས་བཅད་དང་སྡོམ་བྱང་དང་མཁས་པའི་ཚུལ་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་བསྟན་བཅོས་སོགས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    71E9:
      image_group_id: I1KG3149
      title: ''
      total_pages: 428
      order: 1
      base_file: 71E9.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
